version: '3'
services:
  whatsapp-http-api:
    build:
      context: .
      dockerfile: ./Dockerfile  # Certifique-se de que o caminho está correto se o Dockerfile estiver no mesmo diretório que o docker-compose.yml
    container_name: whatsapp-http-api
    ports:
      - '3000:3000/tcp'
    environment:
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

  whatsapp-http-api-plus:
    image: devlikeapro/whatsapp-http-api-plus:chrome
    container_name: whatsapp-http-api-plus
    ports:
      - '3001:3000/tcp'  # Alterei a porta exposta para evitar conflito com outro serviço na mesma porta
    volumes:
      - './.sessions:/app/.sessions'
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_API_KEY=321
      - WHATSAPP_SWAGGER_USERNAME=swagger
      - WHATSAPP_SWAGGER_PASSWORD=admin
      - WAHA_DASHBOARD_USERNAME=waha
      - WAHA_DASHBOARD_PASSWORD=waha
    restart: always

  whatsapp-http-api-plus--mongodb:
    image: devlikeapro/whatsapp-http-api-plus:chrome
    container_name: whatsapp-http-api-plus--mongodb
    ports:
      - '3002:3000/tcp'  # Alterei a porta exposta para evitar conflito com outro serviço na mesma porta
    volumes:
      - './.sessions:/app/.sessions'
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_SESSIONS_MONGO_URL=mongodb://mongodb:27017
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017/tcp'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
